apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cloud-gateway"
  namespace: ms
  labels:
    app: "cloud-gateway"
spec:
  selector:
    matchLabels:
      app: "cloud-gateway"
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: 
    template:
      metadata:
        labels:
          app: "cloud-gateway"
      spec:
        containers:
        - name: "cloud-gateway"
          image: aleqxan/foxx
          ports:
          - containerPort: 9999
            name: "cloud-gateway"
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - user-ui
              topologyKey: "kubernetes.io/hostname"



---
apiVersion: v1
kind: Service
metadata:
  name: "cloud-gateway-service"
  namespace: ms
spec:
  selector:
    app: "cloud-gateway"
  type: NodePort
  ports:
  - name: "cloud-gateway-service"
    port: 9999
    targetPort: 9999
    nodeport: 32447