server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

foxx:
  instance:
    preferIpAddress: true
    hostname: foxx-0
  client:
    registerWithFoxx: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://foxx-0.foxx.default.svc.cluster.local:8761/foxx